class_name GameStrings
extends RefCounted

const TABLE := {
	"en": {
		"ready": "Ready",
		"ready_status": "Formation ready. Tap AUTO to start.",
		"running": "Auto battle running.",
		"players": "Victory",
		"enemies": "Defeat",
		"defeat": "Defeat: upgrade, swap formation, or retry.",
		"offline": "Offline reward: +%d gold, +%d essence.",
		"clear": "Clear reward: +%d gold, +%d essence, +%d shards.",
		"reward_line": "+%d Gold   +%d Essence   +%d Shards",
		"gacha": "Gacha",
		"settings": "Menu",
		"retry": "Retry",
		"restart": "Restart",
		"start": "Start",
		"upgrade": "Upgrade",
		"next": "Next",
		"pull_one": "Pull 1",
		"pull_ten": "Pull 10",
		"buy_premium": "Buy Premium",
		"english": "English",
		"thai": "Thai",
		"sound_on": "Sound On",
		"sound_off": "Sound Off",
		"restore": "Restore",
		"restore_pending": "Account restore will connect after backend login is live.",
		"support": "Support",
		"support_pending": "Support email is required before launch.",
		"feedback": "Feedback",
		"feedback_pending": "Tester feedback form: %s",
		"delete_account": "Delete Account",
		"account_deletion_pending": "Account deletion URL is required before launch.",
		"notifications_later": "Notifications: later",
		"odds": "Odds S 2%  A 8%  B 25%  C 35%  D 30%\nPity 80 | 10x A+",
		"hint_start": "Tap AUTO to battle. Tap two hero cards to swap.",
		"hint_loss": "Upgrade once, swap front/back, or retry.",
		"hint_win": "Claim the next wave when ready.",
		"goal_clear_wave1": "Goal: clear Wave 1, then upgrade.",
		"goal_upgrade_ready": "Upgrade ready. Spend gold, then push higher.",
		"goal_reach_wave5": "Goal: reach Wave 5 for bonus shards.",
		"goal_reach_wave10": "Goal: reach the Wave 10 boss for a bigger bonus.",
		"goal_boss_wave10": "Boss wave: use ULTs and watch the front line.",
		"goal_claim_reward": "Claim the reward, then choose upgrade or next wave.",
	},
	"th": {
		"ready": "พร้อม",
		"ready_status": "จัดทีมพร้อมแล้ว แตะ AUTO เพื่อเริ่มสู้",
		"running": "กำลังต่อสู้อัตโนมัติ",
		"players": "ชนะ",
		"enemies": "แพ้",
		"defeat": "แพ้: อัปเกรด สลับตำแหน่ง หรือลองใหม่",
		"offline": "รางวัลออฟไลน์: +%d ทอง, +%d essence",
		"clear": "รางวัลผ่านด่าน: +%d ทอง, +%d essence, +%d shards",
		"reward_line": "+%d ทอง   +%d Essence   +%d Shards",
		"gacha": "กาชา",
		"settings": "เมนู",
		"retry": "ลองใหม่",
		"restart": "เริ่มใหม่",
		"start": "เริ่ม",
		"upgrade": "อัปเกรด",
		"next": "ถัดไป",
		"pull_one": "สุ่ม 1",
		"pull_ten": "สุ่ม 10",
		"buy_premium": "ซื้อเพชร",
		"english": "English",
		"thai": "ไทย",
		"sound_on": "เสียง เปิด",
		"sound_off": "เสียง ปิด",
		"restore": "กู้บัญชี",
		"restore_pending": "ระบบกู้บัญชีจะเชื่อมต่อหลัง backend login พร้อมใช้",
		"support": "ช่วยเหลือ",
		"support_pending": "ต้องตั้งค่าอีเมลช่วยเหลือก่อนเปิดตัว",
		"feedback": "ฟีดแบ็ก",
		"feedback_pending": "ฟอร์มฟีดแบ็ก tester: %s",
		"delete_account": "ลบบัญชี",
		"account_deletion_pending": "ต้องตั้งค่า URL ลบบัญชีก่อนเปิดตัว",
		"notifications_later": "แจ้งเตือน: ภายหลัง",
		"odds": "โอกาส S 2%  A 8%  B 25%  C 35%  D 30%\nการันตี S 80 ครั้ง | สุ่ม 10 ได้ A+",
		"hint_start": "แตะ AUTO เพื่อเริ่มสู้ แตะการ์ดฮีโร่สองใบเพื่อสลับ",
		"hint_loss": "อัปเกรดหนึ่งครั้ง สลับหน้า/หลัง หรือลองใหม่",
		"hint_win": "พร้อมแล้วไปด่านถัดไป",
		"goal_clear_wave1": "เป้าหมาย: ผ่านด่าน 1 แล้วอัปเกรด",
		"goal_upgrade_ready": "อัปเกรดได้แล้ว ใช้ทองแล้วดันต่อ",
		"goal_reach_wave5": "เป้าหมาย: ถึงด่าน 5 เพื่อรับ shards โบนัส",
		"goal_reach_wave10": "เป้าหมาย: ถึงบอส Wave 10 เพื่อรับโบนัสใหญ่",
		"goal_boss_wave10": "ด่านบอส: กด ULT และดูแนวหน้า",
		"goal_claim_reward": "รับรางวัลก่อน แล้วเลือกอัปเกรดหรือไปต่อ",
	},
}

static func text(key: String, language: String = "en") -> String:
	var pack: Dictionary = TABLE.get(language, TABLE["en"])
	return String(pack.get(key, TABLE["en"].get(key, key)))
